name: wasanbon_xmlrpc
version: 0.2.5
description: A library useful for applications or for sharing on pub.dartlang.org.
dependencies:
  http: any
  xml_rpc: any
  yaml: any
  logging: any
dev_dependencies:
  unittest: any
